name: Build
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-24.04
        container:
            image: gcc:16.1
        steps:
            - name: Install CMake
              run: |
                  apt update
                  apt install -y wget tar ninja-build

                  wget https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-x86_64.tar.gz

                  tar -xzf cmake-4.3.3-linux-x86_64.tar.gz -C /opt

                  ln -s /opt/cmake-4.3.3-linux-x86_64/bin/* /usr/local/bin/

            - name: Checkout Project
              uses: actions/checkout@v6.0.3

            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
              with:
                  build-dir: build
                  generator: Ninja
                  c-compiler: gcc
                  cxx-compiler: g++
                  options: |
                      BUILD_TESTS=ON
                      CMAKE_BUILD_TYPE=Release

            - name: Test Project
              uses: threeal/ctest-action@v1.1.0
