name: Coverage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up GCC
              uses: egor-tensin/setup-gcc@v2
              with:
                  version: 16
                  platform: x64

            - name: Install CMake
              uses: ssrobins/install-cmake@v1
              with:
                  version: 4.2.3

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y ninja-build
                  pip install gcovr

            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
              with:
                  build-dir: build
                  generator: Ninja
                  c-compiler: gcc-16
                  cxx-compiler: g++-16
                  options: |
                      ENABLE_TESTING=ON
                      CMAKE_BUILD_TYPE=Debug
                      ENABLE_COVERAGE=ON

            - name: Run tests
              working-directory: build
              run: ctest --output-on-failure

            - name: Generate coverage report
              working-directory: build
              run: |
                  gcovr \
                    -r ${{ github.workspace }} \
                    --xml-pretty \
                    --ignore-errors missing \
                    --gcov-ignore-parse-errors \
                    --exclude-unreachable-branches \
                    -o coverage.xml

            - name: Upload coverage
              uses: codecov/codecov-action@v5
              with:
                  files: build/coverage.xml
                  fail_ci_if_error: true
                  token: ${{ secrets.CODECOV_TOKEN }}
